# Generated by Django 4.0.3 on 2022-04-21 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societyapp', '0004_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='none', max_length=50)),
                ('email', models.EmailField(max_length=25)),
                ('value', models.CharField(max_length=25, null=True)),
                ('message', models.TextField(default='none', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=14)),
                ('flat_buy', models.BooleanField(default=False)),
                ('flat_rent', models.BooleanField(default=False)),
                ('furnished', models.CharField(max_length=100)),
                ('pool', models.BooleanField(null=True)),
                ('gym', models.BooleanField(null=True)),
                ('creche', models.BooleanField(null=True)),
                ('member', models.IntegerField(default=0)),
                ('flat_size', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Visitors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='none', max_length=50)),
                ('gender', models.CharField(max_length=25)),
                ('mobile', models.IntegerField(default=0)),
                ('place', models.CharField(default='none', max_length=100)),
                ('dateTime', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
